export const PRODUCT_CATALOG = [
  // Achocolatados, café e chás
  'Achocolatado em pó',
  'Achocolatado líquido',
  'Café em cápsulas',
  'Café em pó 250g',
  'Café em pó 500g',
  'Café solúvel',
  'Café torrado e moído',
  'Cappuccino em pó',
  'Chá de camomila',
  'Chá de erva-doce',
  'Chá de hortelã',
  'Chá mate',

  // Açúcares, farinhas e ingredientes
  'Açúcar cristal',
  'Açúcar demerara',
  'Açúcar mascavo',
  'Açúcar refinado',
  'Amido de milho',
  'Aveia em flocos',
  'Aveia em flocos finos',
  'Farinha de arroz',
  'Farinha de mandioca',
  'Farinha de milho',
  'Farinha de rosca',
  'Farinha de trigo',
  'Farinha de trigo integral',
  'Farinha de trigo com fermento',
  'Fermento biológico',
  'Fermento químico',
  'Fubá',
  'Leite de coco',
  'Leite em pó',
  'Leite condensado',
  'Coco ralado',
  'Chocolate em pó',
  'Cacau em pó',
  'Mistura para bolo',
  'Gelatina em pó',
  'Gelatina sem sabor',

  // Arroz, feijão e grãos
  'Arroz branco 1kg',
  'Arroz branco 5kg',
  'Arroz integral',
  'Arroz integral 1kg',
  'Arroz parboilizado',
  'Arroz tipo 1',
  'Arroz tipo 1 1kg',
  'Arroz tipo 1 5kg',
  'Feijão branco',
  'Feijão carioca',
  'Feijão carioca 1kg',
  'Feijão preto',
  'Feijão preto 1kg',
  'Feijão vermelho',
  'Grão-de-bico',
  'Lentilha',
  'Milho de pipoca',
  'Milho para canjica',
  'Quinoa',
  'Soja em grãos',

  // Massas e molhos
  'Macarrão espaguete',
  'Macarrão parafuso',
  'Macarrão penne',
  'Macarrão cabelo de anjo',
  'Macarrão instantâneo',
  'Macarrão integral',
  'Massa para lasanha',
  'Massa para pastel',
  'Massa para pizza',
  'Molho de tomate',
  'Molho de tomate tradicional',
  'Molho de tomate sachê',
  'Extrato de tomate',
  'Polpa de tomate',
  'Tomate pelado',
  'Ketchup',
  'Mostarda',
  'Maionese',
  'Molho barbecue',
  'Molho de pimenta',
  'Molho shoyu',
  'Molho inglês',
  'Molho para salada',

  // Óleos, temperos e condimentos
  'Azeite de oliva',
  'Azeite de oliva extravirgem',
  'Óleo de soja',
  'Óleo de girassol',
  'Óleo de milho',
  'Óleo de coco',
  'Vinagre de álcool',
  'Vinagre de maçã',
  'Vinagre balsâmico',
  'Sal refinado',
  'Sal grosso',
  'Sal rosa',
  'Pimenta-do-reino',
  'Páprica doce',
  'Páprica defumada',
  'Orégano',
  'Cominho',
  'Colorau',
  'Açafrão',
  'Canela em pó',
  'Cravo-da-índia',
  'Louro',
  'Tempero completo',
  'Alho em pasta',
  'Caldo de carne',
  'Caldo de galinha',

  // Conservas e enlatados
  'Atum em lata',
  'Sardinha em lata',
  'Milho verde em conserva',
  'Ervilha em conserva',
  'Seleta de legumes',
  'Palmito em conserva',
  'Azeitona verde',
  'Azeitona preta',
  'Pepino em conserva',
  'Champignon',
  'Grão-de-bico em conserva',

  // Padaria e panificação
  'Pão francês',
  'Pão cacetinho',
  'Pão caseiro',
  'Pão de forma',
  'Pão de forma integral',
  'Pão de leite',
  'Pão de queijo',
  'Pão de cachorro-quente',
  'Pão de hambúrguer',
  'Pão sírio',
  'Bisnaguinha',
  'Torrada tradicional',
  'Torrada integral',
  'Baguete',
  'Croissant',
  'Rosca doce',
  'Bolo de chocolate',
  'Bolo de cenoura',
  'Bolo de milho',
  'Cuca',
  'Sonho',
  'Cueca virada',
  'Rapadura',

  // Leite e laticínios
  'Leite integral',
  'Leite integral 1L',
  'Leite desnatado',
  'Leite semidesnatado',
  'Leite zero lactose',
  'Leite em pó integral',
  'Leite em pó desnatado',
  'Bebida láctea',
  'Iogurte natural',
  'Iogurte grego',
  'Iogurte de morango',
  'Iogurte desnatado',
  'Iogurte zero lactose',
  'Manteiga',
  'Manteiga com sal',
  'Manteiga sem sal',
  'Margarina',
  'Requeijão',
  'Requeijão cremoso',
  'Cream cheese',
  'Creme de leite',
  'Nata',
  'Queijo mussarela',
  'Queijo prato',
  'Queijo minas',
  'Queijo parmesão',
  'Queijo colonial',
  'Queijo ricota',
  'Queijo ralado',
  'Queijo cheddar',
  'Queijo cottage',

  // Carnes bovinas
  'Carne moída',
  'Carne bovina',
  'Acém',
  'Alcatra',
  'Contrafilé',
  'Coxão mole',
  'Coxão duro',
  'Patinho',
  'Músculo bovino',
  'Costela bovina',
  'Picanha',
  'Maminha',
  'Fraldinha',
  'Filé mignon',
  'Bife bovino',
  'Carne para panela',
  'Carne para churrasco',
  'Fígado bovino',
  'Coração bovino',
  'Osso para sopa',

  // Frango e aves
  'Frango inteiro',
  'Peito de frango',
  'Filé de peito de frango',
  'Coxa de frango',
  'Sobrecoxa de frango',
  'Coxa e sobrecoxa',
  'Asa de frango',
  'Coração de frango',
  'Moela de frango',
  'Fígado de frango',
  'Frango a passarinho',
  'Frango desfiado',

  // Carne suína e embutidos
  'Carne suína',
  'Bisteca suína',
  'Costela suína',
  'Lombo suíno',
  'Pernil suíno',
  'Barriga suína',
  'Bacon',
  'Banha de porco',
  'Linguiça toscana',
  'Linguiça calabresa',
  'Linguiça de frango',
  'Salsicha',
  'Presunto',
  'Presunto fatiado',
  'Apresuntado',
  'Mortadela',
  'Salame',
  'Peito de peru',

  // Peixes e frutos do mar
  'Filé de tilápia',
  'Tilápia inteira',
  'Filé de merluza',
  'Salmão',
  'Sardinha fresca',
  'Camarão',
  'Bacalhau',

  // Hortifruti — frutas
  'Abacate',
  'Abacaxi',
  'Ameixa',
  'Banana',
  'Banana caturra',
  'Banana prata',
  'Banana maçã',
  'Caqui',
  'Coco verde',
  'Figo',
  'Goiaba',
  'Kiwi',
  'Laranja',
  'Laranja pera',
  'Limão',
  'Limão siciliano',
  'Maçã',
  'Maçã fuji',
  'Maçã gala',
  'Mamão',
  'Mamão papaia',
  'Manga',
  'Maracujá',
  'Melancia',
  'Melão',
  'Mexerica',
  'Morango',
  'Pera',
  'Pêssego',
  'Tangerina',
  'Uva',
  'Uva verde',
  'Uva roxa',

  // Hortifruti — verduras e legumes
  'Abóbora',
  'Abobrinha',
  'Acelga',
  'Agrião',
  'Alface',
  'Alface americana',
  'Alface crespa',
  'Alface lisa',
  'Alho',
  'Alho-poró',
  'Batata',
  'Batata inglesa',
  'Batata-doce',
  'Berinjela',
  'Beterraba',
  'Brócolis',
  'Cebola',
  'Cebola roxa',
  'Cebolinha',
  'Cenoura',
  'Chuchu',
  'Coentro',
  'Couve',
  'Couve-flor',
  'Espinafre',
  'Gengibre',
  'Inhame',
  'Mandioca',
  'Mandioquinha',
  'Milho verde',
  'Pepino',
  'Pimentão',
  'Pimentão amarelo',
  'Pimentão verde',
  'Pimentão vermelho',
  'Rabanete',
  'Repolho',
  'Repolho roxo',
  'Rúcula',
  'Salsa',
  'Salsão',
  'Tomate',
  'Tomate cereja',
  'Vagem',

  // Ovos
  'Ovos brancos',
  'Ovos vermelhos',
  'Ovos caipiras',
  'Ovos de codorna',
  'Ovos 12 unidades',
  'Ovos 20 unidades',
  'Ovos 30 unidades',

  // Bebidas
  'Água mineral',
  'Água mineral 500ml',
  'Água mineral 1,5L',
  'Água mineral 5L',
  'Água com gás',
  'Água de coco',
  'Refrigerante cola 2L',
  'Refrigerante cola lata',
  'Refrigerante cola zero 2L',
  'Refrigerante guaraná 2L',
  'Refrigerante guaraná zero',
  'Refrigerante laranja',
  'Refrigerante limão',
  'Suco de laranja',
  'Suco de uva',
  'Suco de maçã',
  'Suco integral de uva',
  'Suco em pó',
  'Néctar de frutas',
  'Água tônica',
  'Isotônico',
  'Energético',
  'Bebida vegetal de aveia',
  'Bebida vegetal de soja',
  'Bebida vegetal de amêndoas',

  // Biscoitos, doces e snacks
  'Biscoito recheado',
  'Biscoito de chocolate',
  'Biscoito de maizena',
  'Biscoito cream cracker',
  'Biscoito água e sal',
  'Biscoito integral',
  'Biscoito de polvilho',
  'Bolacha maria',
  'Bolacha caseira',
  'Wafer',
  'Rosquinha',
  'Chocolate ao leite',
  'Chocolate meio amargo',
  'Chocolate branco',
  'Bombom',
  'Caixa de bombons',
  'Barra de cereal',
  'Paçoca',
  'Pé de moleque',
  'Doce de leite',
  'Goiabada',
  'Geleia de morango',
  'Geleia de frutas',
  'Mel',
  'Bala',
  'Pirulito',
  'Chiclete',
  'Marshmallow',
  'Salgadinho',
  'Batata chips',
  'Pipoca de micro-ondas',
  'Amendoim torrado',
  'Amendoim japonês',
  'Castanha-de-caju',
  'Castanha-do-pará',
  'Nozes',
  'Uva-passa',
  'Granola',

  // Congelados e alimentos prontos
  'Pizza congelada',
  'Lasanha congelada',
  'Hambúrguer congelado',
  'Nuggets de frango',
  'Batata frita congelada',
  'Pão de queijo congelado',
  'Legumes congelados',
  'Ervilha congelada',
  'Milho congelado',
  'Açaí congelado',
  'Sorvete',
  'Picolé',
  'Polpa de fruta',
  'Massa de pastel',
  'Empanado de frango',
  'Almôndega congelada',

  // Higiene pessoal
  'Sabonete',
  'Sabonete líquido',
  'Shampoo',
  'Condicionador',
  'Creme para pentear',
  'Máscara capilar',
  'Desodorante',
  'Desodorante aerosol',
  'Desodorante roll-on',
  'Creme dental',
  'Escova de dentes',
  'Fio dental',
  'Enxaguante bucal',
  'Papel higiênico',
  'Papel higiênico 4 rolos',
  'Papel higiênico 12 rolos',
  'Papel higiênico 16 rolos',
  'Lenço de papel',
  'Lenço umedecido',
  'Algodão',
  'Cotonete',
  'Absorvente',
  'Protetor diário',
  'Fralda descartável',
  'Fralda geriátrica',
  'Aparelho de barbear',
  'Espuma de barbear',
  'Hidratante corporal',
  'Protetor solar',
  'Álcool em gel',
  'Preservativo',

  // Limpeza doméstica
  'Detergente',
  'Detergente neutro',
  'Detergente de coco',
  'Sabão em pó',
  'Sabão em pó 1kg',
  'Sabão em pó 2kg',
  'Sabão líquido',
  'Sabão em barra',
  'Sabão de coco',
  'Amaciante',
  'Amaciante concentrado',
  'Alvejante',
  'Água sanitária',
  'Desinfetante',
  'Desinfetante de eucalipto',
  'Desinfetante de lavanda',
  'Limpador multiuso',
  'Limpador de banheiro',
  'Limpa-vidros',
  'Limpa pisos',
  'Limpa alumínio',
  'Saponáceo',
  'Tira-manchas',
  'Álcool 70%',
  'Álcool doméstico',
  'Esponja de cozinha',
  'Esponja de aço',
  'Palha de aço',
  'Pano de chão',
  'Pano multiuso',
  'Luva de limpeza',
  'Vassoura',
  'Rodo',
  'Pá de lixo',
  'Saco de lixo 15L',
  'Saco de lixo 30L',
  'Saco de lixo 50L',
  'Saco de lixo 100L',
  'Papel toalha',
  'Guardanapo',
  'Papel alumínio',
  'Papel filme',
  'Filtro de papel para café',
  'Fósforo',
  'Vela',
  'Inseticida',
  'Repelente',

  // Utilidades
  'Copo descartável',
  'Prato descartável',
  'Talher descartável',
  'Canudo',
  'Pote plástico',
  'Saco plástico',
  'Saco para congelamento',
  'Pilha AA',
  'Pilha AAA',
  'Lâmpada LED',
  'Carvão vegetal',
  'Acendedor de churrasqueira',

  // Produtos para pets
  'Ração para cães',
  'Ração para cães adultos',
  'Ração para cães filhotes',
  'Ração para gatos',
  'Ração para gatos adultos',
  'Ração para gatos filhotes',
  'Ração úmida para cães',
  'Ração úmida para gatos',
  'Sachê para gatos',
  'Sachê para cães',
  'Petisco para cães',
  'Petisco para gatos',
  'Areia sanitária para gatos',
  'Tapete higiênico para cães',
] as const
