export const PRODUCT_CATALOG = [
  'Achocolatado em pó',
  'Açúcar refinado',
  'Água mineral',
  'Arroz integral',
  'Arroz tipo 1',
  'Azeite de oliva',
  'Biscoito recheado',
  'Café em pó 500g',
  'Carne moída',
  'Chocolate ao leite',
  'Creme de leite',
  'Detergente',
  'Farinha de trigo',
  'Feijão carioca',
  'Iogurte natural',
  'Leite de coco',
  'Leite integral',
  'Macarrão espaguete',
  'Manteiga',
  'Óleo de soja',
  'Pão de forma',
  'Papel higiênico',
  'Queijo mussarela',
  'Refrigerante cola 2L',
  'Sabão em pó',
  'Sal refinado',
  'Tomate',
] as const
